export const SET_FRIENDS = 'SET_FRIENDS';
export const SET_SELECTED = 'SET_SELECTED';
export const SET_MESSAGE = 'SET_MESSAGE';
export const SET_CHAT = 'SET_CHAT';
export const ADD_MESSAGE_TO_CHAT = 'ADD_MESSAGE_TO_CHAT';
export const MARK_MESSAGE_AS_SEEN = 'MARK_MESSAGE_AS_SEEN';
